### ISSUE TITLE
Implement Footer

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy-website-2024-astro-vue#1]
Develop  the footer section of the landing page according to the Figma design.

## Tasks
- [ ] Add `OneExercise` link
- [ ] Add `The indieDev` link
- [ ] Add `SelfMastery` link
- [ ] Adjust items placement
